name: self introduction
run-name: âœ¨ ${{ github.actor }} ì˜ ìê¸°ì†Œê°œ âœ¨
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸš€ ${{ github.actor }} ì˜ ìê¸°ì†Œê°œì…ë‹ˆë‹¤. ğŸš€"
      - run: echo "â¤ğŸ§¡ğŸ’›ğŸ’šğŸ’™ğŸ’œğŸ¤ğŸ–¤ğŸ¤"
      - run: echo "${{ github.repository }}."
      - run: echo "ë­ë¼ê³  ì³ì•¼í• ê¹Œìš”."


